import { Navbar } from "@/features/navbar/components/Navbar";
import type { Metadata } from "next";
import { ltSuperior } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ltSuperior.className} antialiased leading-[100%]`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
